# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import temperaturas_pb2 as temperaturas__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in temperaturas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemperaturasStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerTemperaturas = channel.unary_unary(
                '/Temperaturas/ObtenerTemperaturas',
                request_serializer=temperaturas__pb2.Ciudad.SerializeToString,
                response_deserializer=temperaturas__pb2.TemperaturasResponse.FromString,
                _registered_method=True)


class TemperaturasServicer:
    """Missing associated documentation comment in .proto file."""

    def ObtenerTemperaturas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperaturasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerTemperaturas': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerTemperaturas,
                    request_deserializer=temperaturas__pb2.Ciudad.FromString,
                    response_serializer=temperaturas__pb2.TemperaturasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Temperaturas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Temperaturas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Temperaturas:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerTemperaturas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Temperaturas/ObtenerTemperaturas',
            temperaturas__pb2.Ciudad.SerializeToString,
            temperaturas__pb2.TemperaturasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
